name: CTMVanilla
version: 1.0
main: me.vicen621.ctmvanilla.Main
api-version: 1.16
authors: [ Vicen621 ]
description: CTMVanilla plugin

commands:
  guide:
    description: gives the guide to the player
    usage: §c/guide normal | hardmode
  start:
    description: start the game
    usage: §c/start normal | hardmode
    permission: ctm.op
  uhc:
    description: toggles the uhc game mode
    usage: §c/uhc
    permission: ctm.op
  ctmvanilla:
    description: reload command
    usage: §c/ctmvanilla reload
    permission: ctm.op
  minerals:
    description: toggles the minerals game mode
    usage: §c/minerals
    permission: ctm.op
  wools:
    description: see the missing items
    usage: §c/wools

permissions:
  ctm.op:
    default: op
