name: CTMVanilla
version: 1.0
main: me.vicen621.ctmvanilla.Main
api-version: 1.16
authors: [ Vicen621 ]
description: CTMVanilla plugin

commands:
  guide:
    description: gives the guide to the player
  start:
    description: start the game
    permission: ctm.op
  uhc:
    description: toggles the uhc game mode
    permission: ctm.op
  ctmvanilla:
    description: reload command
    permission: ctm.op
  minerals:
    description: toggles the minerals game mode
    permission: ctm.op
  wools:
    description: see the missing items
    usage: §c/wools
  timer:
    description: resumes, stops and set the timer
    permission: crm.op

permissions:
  ctm.op:
    default: op
